openapi: "3.1.0"
info:
  title: "Ethereum JSON-RPC Specification"
  description: "A specification of the standard interface for Ethereum clients."
  version: "0.0.0"
components: {}
paths:
  /eth_gasPrice:
    post:
      summary: "eth_gasPrice"
      description: "Returns the current price per gas in wei."
      operationId: "eth_gasPrice"
      responses:
        200:
          description: "Gas price"
          content:
            application/json:
              schema:
                title: "eth_gasPriceResponse"
                type: "object"
                properties:
                  id:
                    title: "RPC Request ID"
                    type: "integer"
                  jsonrpc:
                    title: "jsonrpc version"
                    type: "string"
                    enum:
                      - "2.0"
                  result:
                    title: "Gas price"
                    type: "string"
                    pattern: "^0x([1-9a-f]+[0-9a-f]*|0)$"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              title: "eth_gasPriceRequest"
              type: "object"
              required:
                - "jsonrpc"
                - "method"
                - "params"
                - "id"
              properties:
                jsonrpc:
                  title: "jsonrpc version"
                  type: "string"
                  enum:
                    - "2.0"
                method:
                  title: "RPC Method Name"
                  type: "string"
                  enum:
                    - "eth_gasPrice"
                params:
                  title: "Needed RPC Params"
                  type: "array"
                  prefixItems: []
                  minItems: 0
                  maxItems: 0
                id:
                  title: "RPC Request ID"
                  type: "integer"
            example:
              jsonrpc: "2.0"
              method: "eth_gasPrice"
              params: []
              id: 0
